language: r

sudo: required

# Be strict when checking our package
warnings_are_errors: true

notifications:
  slack:
    secure: aK1YOxL/AxGpLmGfR+VbZxutyRPwek7h/ID2OTCD9DSRXEGvUTA8sZWJtpjePgr/kxbEQ32mx3ouXH2qV6n2nsb8dr/1TUJPZiiscdGAxNhrffLgHmF5d014/CF3rSO2UKHcdqqaE/WtLrTurBbw4q7OyxCnmSMteK7SBUOBptI=
  email: false
